version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      
  pre_build:
    commands:
      - pwd
    #  - docker build -t helloworld_build .
      - ls /efs
      
  build:
    commands:
      - pwd
      - ls /efs
    #  - docker images
     # - docker run helloworld_build
     # - cd /efs/
      #- docker save -o helloworld_build.tar helloworld_build
      #- cd /efs/prova
      #- docker save -o helloworld_build.tar helloworld_build

  post_build:
    commands:
      - pwd
      - ls -a
      - echo "Sono in Post Build"
      - ls /efs
      - ls /efs-mount-point
      - ls /efs/prova
      
artifacts:
  files:
    #- '**/*.tar'
      
