version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      
  pre_build:
    commands:
      - pwd
      - docker build -t helloworld_build .
      - ls /efs
      
  build:
    commands:
      - pwd
      - ls -a
      - docker images
      - docker run helloworld_build
      - cd /efs
      - docker save -o helloworld_build.tar helloworld_build
      - echo "hello" > /efs/CIAONEE.txt

  post_build:
    commands:
      - pwd
      - ls -a
      - echo "Sono in Post Build"
      - docker run helloworld_build echo "sono in run in post build"
      - ls /efs
      - ls /efs-mount-point
      
artifacts:
  files:
    #- '**/*.tar'
      
